@startuml
actor Client as C
participant "MyAccount Method" as M
participant UserManager as U
participant View as V

C -> M : Post Request with Model
M -> M : Check if Model is Valid
M --> C : Return View with Model (if Model is not valid)
M -> U : GetUserAsync
M -> M : Check if User is Null
M --> C : Throw Exception (if User is Null)
M -> M : Check if Email is Changed
M -> U : SetEmailAsync (if Email is Changed)
M -> M : Check if Email Set Successfully
M --> C : Throw Exception (if Email not Set Successfully)
M -> M : Check if Phone Number is Changed
M -> U : SetPhoneNumberAsync (if Phone Number is Changed)
M -> M : Check if Phone Number Set Successfully
M --> C : Throw Exception (if Phone Number not Set Successfully)
M -> V : Set Status Message
M --> C : Redirect to MyAccount
@enduml